### ISSUE TITLE
iCub Python bindings

### ISSUE THREAD

**Issue by jpiabrantes** [robotology/QA#66]
I was having some troubles installing `yarp` so I re-installed Ubuntu and started from a fresh version. I was able to install `yarp` and `icub` from the source files. I installed the python bindings on `yarp` but I wasn't able to install the `icub` python bindings. When I do `import icub` I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joao/github/icub-main/bindings/python/icub.py", line 28, in <module>
    _icub = swig_import_helper()
  File "/home/joao/github/icub-main/bindings/python/icub.py", line 24, in swig_import_helper
    _mod = imp.load_module('_icub', fp, pathname, description)
ImportError: /home/joao/github/icub-main/bindings/python/_icub.so: undefined symbol: _ZN20ClientGazeControllerC1ERN4yarp2os10SearchableE
```

I built `icub` with ICUB_SHARED_LIBRARY set to OFF because when I build it with it ON I get an error when starting iCub_SIM:

```
iCub_SIM: error while loading shared libraries: libiKin.so.0: cannot open shared object file: No such file or directory
```

Any ideas?

**Comment by Tobias-Fischer** [comment]
Hi,
I've quickly tested doing the same, and I run into the same error. I guess this is because the generated `_icub.so` links against some other libraries which are not found in return. Can you try putting `/path/to/install/yarp/lib` and `/path/to/install/icub-main/lib` in your `LD_LIBRARY_PATH`? This should fix the problem I guess.

Furthermore, delete the following lines from `icub.i`, as they are obsolete (see https://github.com/robotology/QA/issues/33):
```
YARP_DECLARE_DEVICES(icubmod)
YARP_REGISTER_DEVICES(icubmod)
```

Best,
Tobias

CC @pattacini @drdanz

**Comment by pattacini** [comment]
@jpiabrantes, is @Tobias-Fischer's suggestion a good workaround?

**Comment by lornat75** [comment]
you can also try compiling with rpath; this has recently become default and fixes path problems in .so dependencies without the need to use LD_LIBRARY_PATH. in case you need to pull, recompile, after cleaning cmake cache.

On 30/ott/2015, at 10:23, "Ugo Pattacini" <notifications@github.com<mailto:notifications@github.com>> wrote:


@jpiabrantes<https://github.com/jpiabrantes>, is @Tobias-Fischer<https://github.com/Tobias-Fischer>'s suggestion a good workaround?

**Comment by jpiabrantes** [comment]
@lornat75 I have updated and recompiled `icub`. I still have the same error. Should I also update and recompile yarp?

**Comment by Tobias-Fischer** [comment]
Yes, and install yarp with rpath as well.

**Comment by jpiabrantes** [comment]
I tried to recompile yarp and I got an error that I already described on another github [issue](https://github.com/robotology/QA/issues/63). I will try this again when I fix this issue.

**Comment by Tobias-Fischer** [comment]
@jpiabrantes: Any news on this?

**Comment by jpiabrantes** [comment]
@Tobias-Fischer All good now thanks :+1:

**Comment by Tobias-Fischer** [comment]
How did you solve it? Did you have to set `LD_LIBRARY_PATH`?

**Comment by Tobias-Fischer** [comment]
I just tried this (again), and I am still running in the same issue as mentioned in the first post. Therefore, I reopen this ticket.

**Comment by pattacini** [comment]
Stale issue ...
It'd be worth closing this and - if it's the case - add/edit/report more on proper tracking system.
